/**
 * Redux slice для глобальных настроек приложения.
 * Управляет языком интерфейса и системой локализации.
 * 
 * Переводы:
 * - Поддержка 3 языков: русский (ru), украинский (ua), английский (en)
 * - Полный набор переводов для всех экранов и сообщений
 * - Селекторы для удобного доступа к переводам
 * 
 * State:
 * - language: текущий язык интерфейса
 * - translations: объект со всеми переводами
 * 
 * Actions:
 * - setLanguage: изменение языка интерфейса
 * 
 * Селекторы:
 * - selectLanguage: получение текущего языка
 * - selectT: функция перевода текстов
 */
import { createSlice } from '@reduxjs/toolkit';
import { createSelector } from '@reduxjs/toolkit';

export const translations = {
  ru: {
    signUpWelcome: 'Добро пожаловать! Зарегистрируйтесь',
    signUpToAccount: 'Создайте новый аккаунт',
    registrationSuccess: 'Вы успешно зарегистрированы',
    confirmPassword: 'Подтвердите пароль',
    signingUp: 'Регистрация...',
    passwordsDontMatch: 'Пароли не совпадают',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    logout: 'Выйти',
    logoutFromAccount: 'Выйти из аккаунта',
    // Navigation
    login: 'Войти',
    loggingIn: 'Вход...',
    loginToAccount: 'Войдите в свой аккаунт',
    welcome: 'Добро пожаловать!',
    fillAllFields: 'Пожалуйста, заполните все поля',
    enterValidEmail: 'Введите корректный email адрес',
    loginSuccess: 'Вы успешно вошли в систему',
    forgotPassword: 'Забыли пароль?',
    forgotPasswordTitle: 'Восстановление пароля',
    forgotPasswordDesc:
      'Ссылка для восстановления пароля будет отправлена на ваш email',
    send: 'Отправить',
    or: 'или',
    loginWithGoogle: 'Войти через Google',
    loginWithApple: 'Войти через Apple',
    noAccount: 'Нет аккаунта?',
    signUp: 'Зарегистрироваться',
    email: 'Email',
    password: 'Пароль',
    home: 'Главная',
    hello: 'Привет',
    cart: 'Корзина',
    orders: 'Заказ',
    profile: 'Профиль',
    userNotFound: 'Пользователь не найден',
    invalidCredentials: 'Неверный пароль',

    // Home Screen
    coffeepark: 'CoffeePark',
    catalog: 'Каталог напитков',
    lastOrder: 'Последний заказ',
    repeat: 'Повторить',

    // Categories
    coffee: 'Кофе',
    cold: 'Холодные',
    desserts: 'Десерты',

    // Cart
    emptyCart: 'Корзина пуста',
    emptyCartSubtext: 'Добавьте товары из каталога',
    myLocation: 'Моё местоположение в парке',
    total: 'Итого',
    pay: 'Оплатить (Apple/Google Pay)',

    // Profile
    myPoints: 'Мои баллы',
    of: 'из',
    useFreeCard: 'Использовать бесплатный напиток',
    paymentMethods: 'Платёжные методы',
    addCreditCard: 'Добавьте кредитную карту',
    savedLocations: 'Сохранённые точки встреч',
    pointsInPark: 'Точки в парке',
    settings: 'Настройки',
    notificationsLangTheme: 'Уведомления, язык, тема',

    // Settings
    notifications: 'Уведомления',
    pushNotifications: 'Push-уведомления',
    pushNotificationsDesc: 'Получать уведомления на устройство',
    orderUpdates: 'Обновления заказов',
    orderUpdatesDesc: 'Статус приготовления и доставки',
    promotions: 'Акции и предложения',
    promotionsDesc: 'Специальные предложения и скидки',
    language: 'Язык',
    theme: 'Тема',
    darkTheme: 'Темная тема',
    darkThemeDesc: 'Использовать темное оформление',
    other: 'Другое',
    privacy: 'Конфиденциальность',
    privacyDesc: 'Управление данными',
    help: 'Справка',
    helpDesc: 'Часто задаваемые вопросы',
    about: 'О приложении',
    aboutDesc: 'Версия 1.0.0',

    // Order Status
    orderNumber: 'Заказ',
    currentOrder: 'Текущий заказ',
    previousOrders: 'Предыдущие заказы',
    accepted: 'Принято',
    preparing: 'Готовится',
    courierOnWay: 'Курьер едет',
    courierNearby: 'Курьер рядом (ETA 3 мин)',
    callCourier: 'Позвонить курьеру',
    delivered: 'Доставлен',

    // Payment Methods
    savedCards: 'Сохранённые карты',
    otherPaymentMethods: 'Другие способы оплаты',
    cash: 'Наличные',
    makeDefault: 'Сделать основной',
    default: 'Основная',
    noSavedCards: 'Нет сохранённых карт',
    addCreditCardDesc: 'Добавьте кредитную карту для быстрой оплаты',
    addFirstCard: 'Добавить первую карту',

    // Saved Locations
    savedMeetingPoints: 'Сохранённые точки встреч',
    noSavedPlaces: 'Нет сохранённых мест',
    addPlacesDesc: 'Добавьте места для быстрого выбора точки встречи',
    addFirstPlace: 'Добавить первое место',
    setAsMain: 'Сделать основным',
    defaultLocation: 'По умолчанию',

    // Saved Locations
    savedLocations: 'Сохранённые точки встреч',
    parkLocations: 'Точки в парке',
    default: 'По умолчанию',
    makeDefault: 'Сделать основным',
    noSavedLocations: 'Нет сохранённых мест',
    addLocationsHint: 'Добавьте места для быстрого выбора точки встречи',
    addFirstLocation: 'Добавить первое место',

    // Payment Methods
    paymentMethods: 'Способы оплаты',
    addCard: 'Добавить карту',
    noPaymentMethods: 'Нет способов оплаты',
    addPaymentMethodsHint: 'Добавьте карту или другой способ оплаты',
    addFirstPaymentMethod: 'Добавить способ оплаты',

    // Products
    addToCart: 'Добавить',
    notAvailable: 'Нет в наличии',

    // Common
    back: 'Назад',
    add: 'Добавить',
    edit: 'Редактировать',
    delete: 'Удалить',
    cancel: 'Отмена',
    ok: 'OK',
    save: 'Сохранить',
    retry: 'Повторить',
    loading: 'Загрузка',
    error: 'Ошибка',
    success: 'Успешно',
    productAddedToCart: 'Товар добавлен в корзину',
    itemRemovedFromCart: 'Товар удален из корзины',
    clearCart: 'Очистить корзину',
    clearCartConfirmation: 'Вы уверены, что хотите очистить корзину?',
    clear: 'Очистить',
    cartCleared: 'Корзина очищена',
    cartIsEmpty: 'Корзина пуста',
    continueShopping: 'Продолжить покупки',
    noDefaultLocationSet: 'Не установлена локация по умолчанию',
    noDefaultPaymentMethodSet: 'Не установлен способ оплаты по умолчанию',
    orderCreatedSuccessfully: 'Заказ успешно создан',
    orderItemsAddedToCart: 'Товары из заказа добавлены в корзину',
    callCourierTo: 'Позвонить',
    loadingProfile: 'Загружаем профиль...',
    profileLoadError: 'Не удалось загрузить данные профиля',
    freeCardUsed: 'Бесплатный напиток успешно использован!',
    freeCardError: 'Не удалось использовать бесплатный напиток',
    loadingLocations: 'Загружаем локации...',
    loadLocationsError: 'Не удалось загрузить сохраненные локации',
    addLocation: 'Добавить место',
    selectLocationOnMap: 'Выберите точку на карте для сохранения',
    editLocation: 'Редактировать место',
    editLocationConfirm: 'Изменить',
    deleteLocation: 'Удалить место',
    deleteLocationConfirm: 'Вы уверены, что хотите удалить это место?',
    locationDeleted: 'Место успешно удалено',
    deleteLocationError: 'Не удалось удалить место',
    defaultLocationSet: 'Место по умолчанию установлено',
    setDefaultLocationError: 'Не удалось установить место по умолчанию',
    noSavedLocations: 'Нет сохраненных мест',
    addLocationHint: 'Добавьте места для быстрого выбора при заказе',
    parkLocations: 'Места в парке',
    makeDefault: 'По умолчанию',
    edit: 'Изменить',
    loadingPaymentMethods: 'Загружаем способы оплаты...',
    loadPaymentMethodsError: 'Не удалось загрузить способы оплаты',
    addCard: 'Добавить карту',
    addCardDescription: 'Переход к форме добавления новой карты',
    editCard: 'Редактировать карту',
    editCardConfirm: 'Изменить карту',
    deleteCard: 'Удалить карту',
    deleteCardConfirm: 'Вы уверены, что хотите удалить эту карту?',
    cardDeleted: 'Карта успешно удалена',
    deleteCardError: 'Не удалось удалить карту',
    defaultCardSet: 'Карта по умолчанию установлена',
    setDefaultCardError: 'Не удалось установить карту по умолчанию',
    noPaymentMethods: 'Нет способов оплаты',
    addCardHint: 'Добавьте карту для быстрой оплаты',
    savedCards: 'Сохраненные карты',
    card: 'Карта',
    addNewCard: 'Добавить новую карту',
    loadingProducts: 'Загружаем товары...',
    noProducts: 'Нет товаров',
    noProductsHint: 'Товары появятся здесь после загрузки',
    notAvailable: 'Недоступно',
    call: 'Звонить',
    calling: 'Звоним',
    noCurrentOrders: 'Нет текущих заказов',
    noCurrentOrdersSubtext: 'Ваши активные заказы будут отображаться здесь',
    noPreviousOrders: 'Нет предыдущих заказов',
    noPreviousOrdersSubtext: 'История ваших заказов будет отображаться здесь',

    // About Screen
    aboutCoffeeParkDesc:
      'CoffeePark — сервис для заказа кофе и десертов прямо в парке!',
  },

  ua: {
    signUpWelcome: 'Ласкаво просимо! Зареєструйтесь',
    signUpToAccount: 'Створіть новий акаунт',
    registrationSuccess: 'Ви успішно зареєстровані',
    confirmPassword: 'Підтвердіть пароль',
    signingUp: 'Реєстрація...',
    passwordsDontMatch: 'Паролі не співпадають',
    alreadyHaveAccount: 'Вже є акаунт?',
  logout: 'Вийти',
  logoutFromAccount: 'Вийти з акаунта',
    // Navigation
    login: 'Увійти',
    loggingIn: 'Вхід...',
    loginToAccount: 'Увійдіть у свій акаунт',
    welcome: 'Ласкаво просимо!',
    fillAllFields: 'Будь ласка, заповніть всі поля',
    enterValidEmail: 'Введіть коректну email адресу',
    loginSuccess: 'Ви успішно увійшли в систему',
    forgotPassword: 'Забули пароль?',
    forgotPasswordTitle: 'Відновлення пароля',
    forgotPasswordDesc:
      'Посилання для відновлення пароля буде надіслано на ваш email',
    send: 'Відправити',
    or: 'або',
    loginWithGoogle: 'Увійти через Google',
    loginWithApple: 'Увійти через Apple',
    noAccount: 'Немає акаунта?',
    signUp: 'Зареєструватися',
    email: 'Email',
    password: 'Пароль',
    home: 'Головна',
    hello: 'Привіт',
    cart: 'Кошик',
    orders: 'Замовлення',
    profile: 'Профіль',
    userNotFound: 'Користувача не знайдено',
    invalidCredentials: 'Невірний пароль',

    // Home Screen
    coffeepark: 'CoffeePark',
    catalog: 'Каталог напоїв',
    lastOrder: 'Останнє замовлення',
    repeat: 'Повторити',

    // Categories
    coffee: 'Кава',
    cold: 'Холодні',
    desserts: 'Десерти',

    // Cart
    emptyCart: 'Кошик порожній',
    emptyCartSubtext: 'Додайте товари з каталогу',
    myLocation: 'Моє місцезнаходження в парку',
    total: 'Разом',
    pay: 'Оплатити (Apple/Google Pay)',

    // Profile
    myPoints: 'Мої бали',
    of: 'з',
    useFreeCard: 'Використати безкоштовний напій',
    paymentMethods: 'Платіжні методи',
    addCreditCard: 'Додайте кредитну картку',
    savedLocations: 'Збережені точки зустрічі',
    pointsInPark: 'Точки в парку',
    settings: 'Налаштування',
    notificationsLangTheme: 'Сповіщення, мова, тема',

    // Settings
    notifications: 'Сповіщення',
    pushNotifications: 'Push-сповіщення',
    pushNotificationsDesc: 'Отримувати сповіщення на пристрій',
    orderUpdates: 'Оновлення замовлень',
    orderUpdatesDesc: 'Статус приготування та доставки',
    promotions: 'Акції та пропозиції',
    promotionsDesc: 'Спеціальні пропозиції та знижки',
    language: 'Мова',
    theme: 'Тема',
    darkTheme: 'Темна тема',
    darkThemeDesc: 'Використовувати темне оформлення',
    other: 'Інше',
    privacy: 'Конфіденційність',
    privacyDesc: 'Управління даними',
    help: 'Довідка',
    helpDesc: 'Часто задавані питання',
    about: 'Про додаток',
    aboutDesc: 'Версія 1.0.0',

    // Order Status
    orderNumber: 'Замовлення',
    currentOrder: 'Поточне замовлення',
    previousOrders: 'Попередні замовлення',
    accepted: 'Прийнято',
    preparing: 'Готується',
    courierOnWay: "Кур'єр їде",
    courierNearby: "Кур'єр поруч (ETA 3 хв)",
    callCourier: "Подзвонити кур'єру",
    delivered: 'Доставлено',

    // Payment Methods
    savedCards: 'Збережені картки',
    otherPaymentMethods: 'Інші способи оплати',
    cash: 'Готівка',
    makeDefault: 'Зробити основним',
    default: 'Основна',
    noSavedCards: 'Немає збережених карток',
    addCreditCardDesc: 'Додайте кредитну картку для швидкої оплати',
    addFirstCard: 'Додати першу картку',

    // Saved Locations
    savedMeetingPoints: 'Збережені точки зустрічі',
    noSavedPlaces: 'Немає збережених місць',
    addPlacesDesc: 'Додайте місця для швидкого вибору точки зустрічі',
    addFirstPlace: 'Додати перше місце',
    setAsMain: 'Зробити основним',
    defaultLocation: 'За замовчуванням',

    savedLocations: 'Збережені точки зустрічі',
    parkLocations: 'Точки в парку',
    default: 'За замовчуванням',
    makeDefault: 'Зробити основним',
    noSavedLocations: 'Немає збережених місць',
    addLocationsHint: 'Додайте місця для швидкого вибору точки зустрічі',
    addFirstLocation: 'Додати перше місце',

    // Payment Methods Extended
    paymentMethods: 'Способи оплати',
    addCard: 'Додати картку',
    noPaymentMethods: 'Немає способів оплати',
    addPaymentMethodsHint: 'Додайте картку або інший спосіб оплати',
    addFirstPaymentMethod: 'Додати спосіб оплати',

    // Products
    addToCart: 'Додати',
    notAvailable: 'Немає в наявності',

    // Common
    back: 'Назад',
    add: 'Додати',
    edit: 'Редагувати',
    delete: 'Видалити',
    cancel: 'Скасувати',
    ok: 'OK',
    save: 'Зберегти',
    retry: 'Повторити',
    loading: 'Завантаження',
    error: 'Помилка',
    success: 'Успішно',
    productAddedToCart: 'Товар додано до кошика',
    itemRemovedFromCart: 'Товар видалено з кошика',
    clearCart: 'Очистити кошик',
    clearCartConfirmation: 'Ви впевнені, що хочете очистити кошик?',
    clear: 'Очистити',
    cartCleared: 'Кошик очищено',
    cartIsEmpty: 'Кошик порожній',
    continueShopping: 'Продовжити покупки',
    noDefaultLocationSet: 'Не встановлено локацію за замовчуванням',
    noDefaultPaymentMethodSet: 'Не встановлено спосіб оплати за замовчуванням',
    orderCreatedSuccessfully: 'Замовлення успішно створено',
    orderItemsAddedToCart: 'Товари із замовлення додано до кошика',
    callCourierTo: 'Подзвонити',
    loadingProfile: 'Завантажуємо профіль...',
    profileLoadError: 'Не вдалося завантажити дані профілю',
    freeCardUsed: 'Безкоштовний напій успішно використано!',
    freeCardError: 'Не вдалося використати безкоштовний напій',
    loadingLocations: 'Завантажуємо локації...',
    loadLocationsError: 'Не вдалося завантажити збережені локації',
    addLocation: 'Додати місце',
    selectLocationOnMap: 'Виберіть точку на карті для збереження',
    editLocation: 'Редагувати місце',
    editLocationConfirm: 'Змінити',
    deleteLocation: 'Видалити місце',
    deleteLocationConfirm: 'Ви впевнені, що хочете видалити це місце?',
    locationDeleted: 'Місце успішно видалено',
    deleteLocationError: 'Не вдалося видалити місце',
    defaultLocationSet: 'Місце за замовчуванням встановлено',
    setDefaultLocationError: 'Не вдалося встановити місце за замовчуванням',
    noSavedLocations: 'Немає збережених місць',
    addLocationHint: 'Додайте місця для швидкого вибору при замовленні',
    parkLocations: 'Місця в парку',
    makeDefault: 'За замовчуванням',
    edit: 'Змінити',
    loadingPaymentMethods: 'Завантажуємо способи оплати...',
    loadPaymentMethodsError: 'Не вдалося завантажити способи оплати',
    addCard: 'Додати картку',
    addCardDescription: 'Перехід до форми додавання нової картки',
    editCard: 'Редагувати картку',
    editCardConfirm: 'Змінити картку',
    deleteCard: 'Видалити картку',
    deleteCardConfirm: 'Ви впевнені, що хочете видалити цю картку?',
    cardDeleted: 'Картку успішно видалено',
    deleteCardError: 'Не вдалося видалити картку',
    defaultCardSet: 'Картку за замовчуванням встановлено',
    setDefaultCardError: 'Не вдалося встановити картку за замовчуванням',
    noPaymentMethods: 'Немає способів оплати',
    addCardHint: 'Додайте картку для швидкої оплати',
    savedCards: 'Збережені картки',
    card: 'Картка',
    addNewCard: 'Додати нову картку',
    loadingProducts: 'Завантажуємо товари...',
    noProducts: 'Немає товарів',
    noProductsHint: "Товари з'являться тут після завантаження",
    notAvailable: 'Недоступно',
    call: 'Дзвонити',
    calling: 'Дзвонимо',
    noCurrentOrders: 'Немає поточних замовлень',
    noCurrentOrdersSubtext: 'Ваші активні замовлення будуть відображатися тут',
    noPreviousOrders: 'Немає попередніх замовлень',
    noPreviousOrdersSubtext: 'Історія ваших замовлень буде відображатися тут',

    // About Screen
    aboutCoffeeParkDesc:
      'CoffeePark — сервіс для замовлення кави та десертів просто в парку!',
  },

  en: {
    signUpWelcome: 'Welcome! Sign up',
    signUpToAccount: 'Create a new account',
    registrationSuccess: 'You have successfully registered',
    confirmPassword: 'Confirm password',
    signingUp: 'Signing up...',
    passwordsDontMatch: 'Passwords do not match',
    alreadyHaveAccount: 'Already have an account?',
  logout: 'Logout',
  logoutFromAccount: 'Logout from account',
    // Navigation
    login: 'Login',
    loggingIn: 'Logging in...',
    loginToAccount: 'Log in to your account',
    welcome: 'Welcome!',
    fillAllFields: 'Please fill in all fields',
    enterValidEmail: 'Enter a valid email address',
    loginSuccess: 'You have successfully logged in',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Password recovery',
    forgotPasswordDesc: 'A password reset link will be sent to your email',
    send: 'Send',
    or: 'or',
    loginWithGoogle: 'Login with Google',
    loginWithApple: 'Login with Apple',
    noAccount: 'No account?',
    signUp: 'Sign up',
    email: 'Email',
    password: 'Password',
    home: 'Home',
    hello: 'Hello',
    cart: 'Cart',
    orders: 'Order',
    profile: 'Profile',
    userNotFound: 'user not found',
    invalidCredentials: 'invalid password',

    // Home Screen
    coffeepark: 'CoffeePark',
    catalog: 'Drinks Catalog',
    lastOrder: 'Last Order',
    repeat: 'Repeat',

    // Categories
    coffee: 'Coffee',
    cold: 'Cold',
    desserts: 'Desserts',

    // Cart
    emptyCart: 'Cart is empty',
    emptyCartSubtext: 'Add items from catalog',
    myLocation: 'My location in the park',
    total: 'Total',
    pay: 'Pay (Apple/Google Pay)',

    // Profile
    myPoints: 'My points',
    of: 'of',
    useFreeCard: 'Use free drink',
    paymentMethods: 'Payment methods',
    addCreditCard: 'Add credit card',
    savedLocations: 'Saved meeting points',
    pointsInPark: 'Points in park',
    settings: 'Settings',
    notificationsLangTheme: 'Notifications, language, theme',

    // Settings
    notifications: 'Notifications',
    pushNotifications: 'Push notifications',
    pushNotificationsDesc: 'Receive notifications on device',
    orderUpdates: 'Order updates',
    orderUpdatesDesc: 'Preparation and delivery status',
    promotions: 'Promotions and offers',
    promotionsDesc: 'Special offers and discounts',
    language: 'Language',
    theme: 'Theme',
    darkTheme: 'Dark theme',
    darkThemeDesc: 'Use dark appearance',
    other: 'Other',
    privacy: 'Privacy',
    privacyDesc: 'Data management',
    help: 'Help',
    helpDesc: 'Frequently asked questions',
    about: 'About app',
    aboutDesc: 'Version 1.0.0',

    // Order Status
    orderNumber: 'Order',
    currentOrder: 'Current order',
    previousOrders: 'Previous orders',
    accepted: 'Accepted',
    preparing: 'Preparing',
    courierOnWay: 'Courier on way',
    courierNearby: 'Courier nearby (ETA 3 min)',
    callCourier: 'Call courier',
    delivered: 'Delivered',

    // Payment Methods
    savedCards: 'Saved cards',
    otherPaymentMethods: 'Other payment methods',
    cash: 'Cash',
    makeDefault: 'Make default',
    default: 'Default',
    noSavedCards: 'No saved cards',
    addCreditCardDesc: 'Add credit card for quick payment',
    addFirstCard: 'Add first card',

    // Saved Locations
    savedMeetingPoints: 'Saved meeting points',
    noSavedPlaces: 'No saved places',
    addPlacesDesc: 'Add places for quick meeting point selection',
    addFirstPlace: 'Add first place',
    setAsMain: 'Set as main',
    defaultLocation: 'Default',

    savedLocations: 'Saved meeting points',
    parkLocations: 'Park locations',
    default: 'Default',
    makeDefault: 'Make default',
    noSavedLocations: 'No saved locations',
    addLocationsHint: 'Add places for quick meeting point selection',
    addFirstLocation: 'Add first location',

    // Payment Methods Extended
    paymentMethods: 'Payment methods',
    addCard: 'Add card',
    noPaymentMethods: 'No payment methods',
    addPaymentMethodsHint: 'Add card or other payment method',
    addFirstPaymentMethod: 'Add payment method',

    // Products
    addToCart: 'Add',
    notAvailable: 'Not available',

    // Common
    back: 'Back',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    ok: 'OK',
    save: 'Save',
    retry: 'Retry',
    loading: 'Loading',
    error: 'Error',
    success: 'Success',
    productAddedToCart: 'Product added to cart',
    itemRemovedFromCart: 'Item removed from cart',
    clearCart: 'Clear cart',
    clearCartConfirmation: 'Are you sure you want to clear the cart?',
    clear: 'Clear',
    cartCleared: 'Cart cleared',
    cartIsEmpty: 'Cart is empty',
    continueShopping: 'Continue shopping',
    noDefaultLocationSet: 'No default location set',
    noDefaultPaymentMethodSet: 'No default payment method set',
    orderCreatedSuccessfully: 'Order created successfully',
    orderItemsAddedToCart: 'Order items added to cart',
    callCourierTo: 'Call',
    loadingProfile: 'Loading profile...',
    profileLoadError: 'Failed to load profile data',
    freeCardUsed: 'Free drink successfully used!',
    freeCardError: 'Failed to use free drink',
    loadingLocations: 'Loading locations...',
    loadLocationsError: 'Failed to load saved locations',
    addLocation: 'Add location',
    selectLocationOnMap: 'Select a point on the map to save',
    editLocation: 'Edit location',
    editLocationConfirm: 'Change',
    deleteLocation: 'Delete location',
    deleteLocationConfirm: 'Are you sure you want to delete this location?',
    locationDeleted: 'Location successfully deleted',
    deleteLocationError: 'Failed to delete location',
    defaultLocationSet: 'Default location set',
    setDefaultLocationError: 'Failed to set default location',
    noSavedLocations: 'No saved locations',
    addLocationHint: 'Add locations for quick selection when ordering',
    parkLocations: 'Park locations',
    makeDefault: 'Make default',
    edit: 'Edit',
    loadingPaymentMethods: 'Loading payment methods...',
    loadPaymentMethodsError: 'Failed to load payment methods',
    addCard: 'Add card',
    addCardDescription: 'Go to new card addition form',
    editCard: 'Edit card',
    editCardConfirm: 'Change card',
    deleteCard: 'Delete card',
    deleteCardConfirm: 'Are you sure you want to delete this card?',
    cardDeleted: 'Card successfully deleted',
    deleteCardError: 'Failed to delete card',
    defaultCardSet: 'Default card set',
    setDefaultCardError: 'Failed to set default card',
    noPaymentMethods: 'No payment methods',
    addCardHint: 'Add a card for quick payment',
    savedCards: 'Saved cards',
    card: 'Card',
    addNewCard: 'Add new card',
    loadingProducts: 'Loading products...',
    noProducts: 'No products',
    noProductsHint: 'Products will appear here after loading',
    notAvailable: 'Not available',
    call: 'Call',
    calling: 'Calling',
    noCurrentOrders: 'No current orders',
    noCurrentOrdersSubtext: 'Your active orders will be displayed here',
    noPreviousOrders: 'No previous orders',
    noPreviousOrdersSubtext: 'Your order history will be displayed here',

    // About Screen
    aboutCoffeeParkDesc:
      'CoffeePark is a service for ordering coffee and desserts right in the park!',
  },
};

const initialState = {
  language: 'ru',
};

export const appSlice = createSlice({
  name: 'app',
  initialState,
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
    },
  },
});

export const { setLanguage } = appSlice.actions;

export const selectLanguage = (state) => state.app.language;

export const selectT = createSelector(
  [selectLanguage],
  (language) => (key) => {
    return translations[language]?.[key] || key;
  }
);

export default appSlice.reducer;
